name: pwsh-script

on:
  schedule:
    - cron: "30 1 * * *"
    - cron: "30 6 * * *"
    - cron: "30 12 * * *"
  workflow_dispatch:
jobs:
  run:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run script
        env:
          IS_AT_SCHOOL: ${{ secrets.IS_AT_SCHOOL }}
          BUPT_USERNAME: ${{ secrets.BUPT_USERNAME }}
          BUPT_PASSWORD: ${{ secrets.BUPT_PASSWORD }}
        run: |
          ./main.ps1
